function mt=fgeom2mt(strike,rake,dip,M0)
% This function is used to transform the fault geometry to the corresponding moment tensor of the fault.
% The convention of coordinate systerm follows the definition in Aki & Richards 2002, Fig 4.20 and BOX 4.4.
% Right-hand coordinate systerm in Cartesian coordinate.
% X: North; Y: East; Z: vertical down.
% Azimuth angle is measured from the positive X-axis to positive Y-axis
% (i.e. positive X-axis is 0, positive Y-axis is pi/2), range: [0, 2pi).
% Unit of angle: degree. Unit of M0: N*m.
% Note the moment tensor generated by fault geometries is not been
% normalized. The module of is may be not 1.
% INPUT:-------------------------------------------------
% strike: azimuth of the fault plane, in degree.
% rake: slip angle of the fault along the strike direction, in degree.
% dip: dip anlge of the fault plane, in degree.
% M0: scalar moment, in N*m.
% OUTPUT:----------------------------------------------
% mt: the Cartesian moment tensor of the fault, 3*3 matrix.
% [mxx  mxy  mxz
%  myx  myy  myz
%  mzx  mzy  mzz].

% set default value
if nargin<4
    M0=1;
end

mt=zeros(3,3);

mt(1,1)=-M0*(sind(dip)*cosd(rake)*sind(2*strike)+sind(2*dip)*sind(rake)*sind(strike)^2); % mxx
mt(1,2)= M0*(sind(dip)*cosd(rake)*cosd(2*strike)+0.5*sind(2*dip)*sind(rake)*sind(2*strike)); % mxy
mt(1,3)=-M0*(cosd(dip)*cosd(rake)*cosd(strike)+cosd(2*dip)*sind(rake)*sind(strike)); % mxz
mt(2,2)= M0*(sind(dip)*cosd(rake)*sind(2*strike)-sind(2*dip)*sind(rake)*cosd(strike)^2); % myy
mt(2,3)=-M0*(cosd(dip)*cosd(rake)*sind(strike)-cosd(2*dip)*sind(rake)*cosd(strike)); % myz
mt(3,3)= M0*sind(2*dip)*sind(rake); % mzz
mt(2,1)=mt(1,2); % myx
mt(3,1)=mt(1,3); % mzx
mt(3,2)=mt(2,3); % mzy

end